"""add chat_session table and relationships

Revision ID: 005147f1d74e
Revises: e2cd2430b4a5
Create Date: 2025-12-10 03:39:49.340260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005147f1d74e'
down_revision: Union[str, Sequence[str], None] = 'e2cd2430b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guest_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('top_intent', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_guest_messages_session_id', 'chat_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_guest_messages_session_id', type_='foreignkey')
        batch_op.drop_column('session_id')

    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
