"""Add security fields

Revision ID: 324a5f04668b
Revises: bbeea3a5121a
Create Date: 2025-12-24 15:38:22.887031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324a5f04668b'
down_revision: Union[str, Sequence[str], None] = 'bbeea3a5121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gemini_api_key', sa.String(), nullable=True))

    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_messages_per_session', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_sessions_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whitelisted_domains', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.drop_column('whitelisted_domains')
        batch_op.drop_column('max_sessions_per_day')
        batch_op.drop_column('max_messages_per_session')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('gemini_api_key')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
