"""add_welcome_and_initial_ai_message

Revision ID: e2cd2430b4a5
Revises: bcd65c085afb
Create Date: 2025-12-09 03:03:45.520193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cd2430b4a5'
down_revision: Union[str, Sequence[str], None] = 'bcd65c085afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('welcome_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('initial_ai_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('send_initial_message_automatically', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_settings', schema=None) as batch_op:
        batch_op.drop_column('send_initial_message_automatically')
        batch_op.drop_column('initial_ai_message')
        batch_op.drop_column('welcome_message')

    # ### end Alembic commands ###
